export const nameKey = Symbol()
export const passwordKey = Symbol()
export const confirmPasswordKey = Symbol()
export const sortKey = Symbol()
export const searchKey = Symbol()
export const emojisCloseKey = Symbol()
export const emojiKey = Symbol()
